### ISSUE TITLE
[Story] Create Routing system for the app

### ISSUE THREAD

**Issue by ErkinKurt** [aaliboyaci/react-movie-database#1]
Create Routing Structure for application. 

I'd like to be able to use this urls and populate the data according to url parameters. 

github.aliboyaci.movie.app.com/home?searchPattern=dovuskulubu 
github.aliboyaci.movie.app.com/movieDetail/123123124324123123

**Comment by aaliboyaci** [comment]
Nav Tree for the app


![Image](https://github.com/aaliboyaci/react-movie-database/assets/121137857/feca6c0d-a70d-4b4d-a3fc-6eb52348b42c)

**Comment by aaliboyaci** [comment]
React routes has been created for all the pages.
Links are working propoerly.
Only creating urls like:
github.aliboyaci.movie.app.com/home?searchPattern=dovuskulubu
github.aliboyaci.movie.app.com/movieDetail/123123124324123123
is left. And i will do that after the fetching process.
at this point i am going to start next task. i believe i can close this task after fetching and using useParams etc.

**Comment by aaliboyaci** [comment]
ive done  fetch opoerations through "search" and then right now i have urls like
github.aliboyaci.movie.app.com/home?searchPattern=dovuskulubu
github.aliboyaci.movie.app.com/movieDetail/123123124324123123
etc.
at this point i believe creating and using ReactRouter task is done.
