### ISSUE TITLE
Display selected genre list

### ISSUE THREAD

**Issue by ozerbet** [aaliboyaci/react-movie-database#12]
See rel

[UC- Genres.docx](https://github.com/aaliboyaci/react-movie-database/files/11878367/UC-.Genres.docx)

ated usecase for details.

**Comment by aaliboyaci** [comment]
selected genre from "genres page" is perfectly working right now. and also i have handled api responses via "&page=" parametre so that system can handle 9 million show right now from Genres tab or search.

also i think this feature looks and works awesome
