### ISSUE TITLE
Implement watch list page

### ISSUE THREAD

**Issue by ozerbet** [aaliboyaci/react-movie-database#13]
See related usecase for details. 

[UC- Watch List.docx](https://github.com/aaliboyaci/react-movie-database/files/11878619/UC-.Watch.List.docx)

**Comment by aaliboyaci** [comment]
System displays 20 movies per page, 4 movies per row. - done

![Image](https://github.com/aaliboyaci/react-movie-database/assets/121137857/ab89e23e-f0a2-4467-a4d9-f295c1d82f54)
![Image](https://github.com/aaliboyaci/react-movie-database/assets/121137857/46e6b5af-27e2-4cd5-b443-854561402cde)

--Right now user can add to favourites movies to the watchlist, and can display those from watchlist page by organized card listing. 5x4. Also from watch list page, user can use links to go to details page of the fav movies and can remove them from the fav list.
