### ISSUE TITLE
Add default movie poster for movies without poster

### ISSUE THREAD

**Issue by ozerbet** [aaliboyaci/react-movie-database#28]
![Image](https://github.com/aaliboyaci/react-movie-database/assets/34393643/15c916e5-beb4-4cd3-bdcd-4afaea49d01e)
![Image](https://github.com/aaliboyaci/react-movie-database/assets/34393643/97188e35-8305-49d7-8f20-6ab294460d92)

**Comment by aaliboyaci** [comment]
task is done, 
#31
